build:
  image: golang:1-alpine
  stage: build
  cache:
    paths:
    - .cache
  variables:
    CGO_ENABLED: 0
  before_script:
  - apk add git build-base
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
  - env GOOS=linux GOARCH=amd64 go build -o zeroparse-linux-amd64
  - env GOOS=linux GOARCH=arm64 go build -o zeroparse-linux-arm64
  - env GOOS=linux GOARCH=arm go build -o zeroparse-linux-arm
  - env GOOS=darwin GOARCH=amd64 go build -o zeroparse-darwin-amd64
  - env GOOS=darwin GOARCH=arm64 go build -o zeroparse-darwin-arm64
  artifacts:
    paths:
    - zeroparse-*
